version: '3.8'

services:
  # 1) Go backend (Telegram bot + REST-ish entrypoint if you add endpoints)
  lvlchess_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lvlchess_go
    ports:
      - "8080:8080"
    # depends_on:
      # - lvlchess_db
      # - lvlchess_redis
      # Uncomment if you plan to use NATS subject streaming
      # - lvlchess_nats
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    # You could override the default CMD by specifying "command" below
    # command: ["./lvlchess", "--some-flag"]
    # environment:
    #   PG_HOST: "lvlchess_db"

#  # 2) Redis in-memory store (optionally used for caching)
#  lvlchess_redis:
#    image: redis:7-alpine
#    container_name: lvlchess_redis
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - ./redis_data:/data
#    ports:
#      - "6379:6379"
#
#  # 3) PostgreSQL for persisting users, rooms, tournaments
#  lvlchess_db:
#    image: postgres:14-alpine
#    container_name: lvlchess_db
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: pass
#      POSTGRES_DB: lvlchess
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
#  # 4) NATS (JetStream) – optional for microservice/event-driven approaches
#  lvlchess_nats:
#    image: nats:2.10.11
#    container_name: lvlchess_nats
#    command: ["--jetstream", "--store_dir=/data"]
#    volumes:
#      - ./nats_data:/data
#    ports:
#      - "4222:4222"
#      - "8222:8222"
#
#  # (Optional) NATS exporter for Prometheus
#  lvlchess_nats_exporter:
#    image: synadia/nats-prometheus-exporter
#    container_name: lvlchess_nats_exporter
#    depends_on:
#      - lvlchess_nats
#    environment:
#      GATEWAY_URL: "http://lvlchess_nats:8222/varz"
#    ports:
#      - "7777:7777"

  # 5) Frontend (React) – minimal example
  lvlchess_front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lvlchess_front
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - lvlchess_go

#  # 6) Prometheus – optional for monitoring
#  lvlchess_prometheus:
#    image: prom/prometheus:latest
#    container_name: lvlchess_prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - lvlchess_go
#      - lvlchess_nats
#      - lvlchess_db
#
#  # 7) Grafana – optional for real-time metrics dashboards
#  lvlchess_grafana:
#    image: grafana/grafana:latest
#    container_name: lvlchess_grafana
#    ports:
#      - "3001:3000"
#    volumes:
#      - ./grafana_data:/var/lib/grafana
#    depends_on:
#      - lvlchess_prometheus
