telegram:
  token: "YOUR_BOT_TOKEN"
  timeout: 60
  debug: false

game:
  default_time_limit: 300  # 5 minutes
  time_controls:
    - 60    # 1 minute
    - 300   # 5 minutes
    - 1800  # 30 minutes
    - 3600  # 1 hour
    - 0     # No limit

logging:
  level: "info"
  format: "json"
  file: "logs/chessbot.log" 